### ISSUE TITLE
Missing MR in release 0.30.0 documentation

### ISSUE THREAD

**Issue by Sinscerly** [gardener/gardener-metrics-exporter#106]
**What happened**:

[104](https://github.com/gardener/gardener-metrics-exporter/pull/104) is missing in the release documentation.
```Add is_workerless to the garden_shoot_info metric```

@vicwicker

**Comment by vicwicker** [comment]
@Sinscerly I am sorry. I missed to check the PR description was using the markdown correctly for the notes to be automatically generated. I fixed them for 0.30.0 manually.

Thanks for letting us know.

**Comment by Sinscerly** [comment]
Thanks for updating ❤️ Can happen everyone.
