### ISSUE TITLE
AKS Cluster (garden and seed) upgrade to k8s v1.12.5 is not supported by Gardener v0.15.2

### ISSUE THREAD

**Issue by praveendhac** [gardener/gardener-metrics-exporter#14]
Azure AKS Cluster (garden and seed) upgrade to k8s v1.12.5 is not supported by Gardener v0.15.2, as per out chat on slack it should support.
```
praveend [12:58 PM]
@rfranzke which version of gardener supports AKS v1.12.5, didn't find much information in gardener release notes. Upgrading gardener is the only option as Azure doesn't support AKS k8s downgrade.

rfranzke [12:59 PM]
Any version of Gardener that supports 1.12 itself for shoot clusters, so any version 0.13.0+
```
Gardener Version: 0.15.2
AKS version: 1.12.5 (upgraded from 1.11.5)

Log from metrics server
```
$ kubectl logs gardener-metrics-exporter-5f5dbf6767-cvbvp -n garden
time="2019-02-18T11:21:36Z" level=error msg="Kubernetes cluster has version v1.12.5 which is not supported"
```

**Comment by rfranzke** [comment]
@praveendhac I still don’t understand why you are talking about the Gardener version when you actually are posting the logs of the metrics-exporter. I‘ve moved the issue accordingly to this repo.

**Comment by praveendhac** [comment]
@rfranzke When I upgraded AKS from v1.11.5 to 1.12.5, all the pods in `gardener` namespace came up healthy except `gardener-metrics-exporter` so posting the logs of metrics-exporter Pod. Probably, the issue is only with metrics exporter pod/container.

```
$ kubectl get po -n garden
NAME                                           READY   STATUS             RESTARTS   AGE
etcd-msa-infra-0                               2/2     Running            0          5d
gardener-apiserver-78bb45ddbc-n6md5            1/1     Running            0          4d17h
gardener-controller-manager-5b66475646-9llm4   1/1     Running            7          5d
gardener-metrics-exporter-5f5dbf6767-sw256     0/1     CrashLoopBackOff   595        2d2h

# image used
    image: eu.gcr.io/gardener-project/gardener/metrics-exporter:0.1.0-dev-8fde706255c44c8f39aeb76ab0563f953e485c40
    imagePullPolicy: IfNotPresent
    name: gardener-metrics-exporter
```

**Comment by dkistner** [comment]
Hi @praveendhac Seems that you use a be a pretty old version of the metrics-exporter. Could you try the most recent version `0.3.0`?

**Comment by praveendhac** [comment]
That is the default `metrics-exporter` Server coming as part of gardener deployment, will try the latest one.

**Comment by rfranzke** [comment]
> That is the default `metrics-exporter` Server coming as part of gardener deployment, will try the latest one.

The gardener-metrics-exporter is not coming with the Gardener Helm chart, it's a separate chart/deployment.

**Comment by vlerenc** [comment]
Any settlement on this one?

**Comment by dkistner** [comment]
This issue should be resolved with a more recent version that the referenced one.
I will therefore close this issue.
