### ISSUE TITLE
Add new metric garden_shoot_total

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener-metrics-exporter#31]
**What would you like to be added**:
There should be a metric `garden_shoot_total` to track how many shoots have been created in total

**Comment by dkistner** [comment]
Are we not able to calculate those metric based on the available metrics for shoots?

**Comment by wyb1** [comment]
@dkistner it's possible to do `count(garden_shoot_info)` to view how many total shoots we have right now, but there is no way to compare how many total shoots have been created between two points in time.
