### ISSUE TITLE
metrics decoration improvements

### ISSUE THREAD

**Issue by bergerx** [gardener/gardener-metrics-exporter#4]
We are thinking about using this project to build dashboards but some missing tags are bothering us to build more effective dashboards.

Some improvement ideas:
* `garden_shoot_condition` and `garden_shoot_operation_states` should also have `seed` and `iaas` tag so that we can filter or group by the `ControlPlaneHealthy` conditions and `garden_shoot_operation_states` based on seed or cloud. I'd vote for adding `project`, `seed` and `iaas` tags to all specific shoot related metrics at all.
* `garden_shoot_operation_states` should have a `state` tag that tells about how the last operation is resulted. 

For botb above `garden_shoot_operations_total` has the extra information is required information but doing join-like operations on prometheus is not really feasible so to create not-so-complex-dashboards the tags should be available in the immediate metrics and should not be collected with some extra queries.

Here is an example about what we have as of today:
``` garden_shoot_condition{condition="ControlPlaneHealthy",mail_to="",name="axeda",operation="Reconcile",project="consus",purpose=""} 1
garden_shoot_condition{condition="EveryNodeReady",mail_to="",name="axeda",operation="Reconcile",project="consus",purpose=""} 1
garden_shoot_condition{condition="SystemComponentsHealthy",mail_to="",name="axeda",operation="Reconcile",project="consus",purpose=""} 1
garden_shoot_info{iaas="azure",name="axeda",project="consus",region="eastus",seed="azure-eastus-01",version="1.11.2"} 0
garden_shoot_node_max_total{name="axeda",project="consus"} 10
garden_shoot_node_min_total{name="axeda",project="consus"} 2
garden_shoot_operation_states{mail_to="",name="axeda",operation="Create",project="consus"} 0
garden_shoot_operation_states{mail_to="",name="axeda",operation="Delete",project="consus"} 0
garden_shoot_operation_states{mail_to="",name="axeda",operation="Reconcile",project="consus"} 1
```

**Comment by bergerx** [comment]
Also if these improvements are ok for you we are willing to implement these (@alcasim), just let us know.

**Comment by dkistner** [comment]
Thanks @bergerx for the proposal.

FYI: We plan to provide some dashboards for the metrics of the exporter. The PR is already filed https://github.com/gardener/gardener-metrics-exporter/pull/6. May this fits already to some your needs. Please feel free to try out and provide feedback.

Basically I'm fine with extending the metrics in the manner you suggested. Are there other reason for the extension than just avoiding joins? In the provided dashboards we are also using joins and they seems to work well.

**Comment by bergerx** [comment]
Wow that's cool we'll check it shortly

> Are there other reason for the extension than just avoiding joins?
Not really, current set of tags could work for a purposely designed dashboards. But we still want to show shoot/seed/iaas related information also in other dashboards without having to run extra queries if possible.

**Comment by dkistner** [comment]
The `.conditions[].status` is reflected by value of the metric see here: https://github.com/gardener/gardener-metrics-exporter/blob/master/pkg/metrics/utils.go#L31-L42. 
The value of the `.conditions[].reason` field is at least specific per condition and would lead to high label cardinality and its therefore not a good idea to have it as label, because we want to archive one timeseries per condition and we would get for every reason a new timeseries. It's the same for the `.conditions[].message`. The `operation` field of the condition goes in the same direction, but it could produce only a small cardinality (`Create|Delete|Reconcile`). But I have to check if this is still required.

**Comment by bergerx** [comment]
Hmmm, encoding distinct values to a metric doesnt seem right, will require us to copy the enum value decode logic to dashboards we use this metrics.
But at least we have the info available to consume.

So maybe the `reason` would be the only field that would be added. I don't know if it would make sense. I'm closing this issue anyway we can create another one if we need.

Thanks for the comments.

**Comment by dkistner** [comment]
> Hmmm, encoding distinct values to a metric doesnt seem right, will require us to copy the enum value decode logic to dashboards we use this metrics.

Yeah that's right unfortunately you need to duplicate the enum value within a dashboard. The value of the metric `garden_shoot_condition` should reflect the current status of a condition. The status of a condition could have the value `True|False|Unknown`. Prometheus allow only to store floats for metric values (that's the reason why we need this mapping). Labels are basically meant as identifiers and for selection of those metrics and should therefore not contain any status information.
