### ISSUE TITLE
Expose min/max node count of specific worker groups

### ISSUE THREAD

**Issue by wyb1** [gardener/gardener-metrics-exporter#45]
**What would you like to be added**:

We currently only expose the total min/max nodes of a shoot. In addition to this the min/max nodes of each worker group should be exposed.

**Comment by Sinscerly** [comment]
This is a simple implementation. It's working great and collects the worker group total min/max nodes of a shoot. Also lists the group machine type which is handy information the garden metrics exporter not yet exposed.

https://github.com/Sinscerly/gardener-metrics-exporter/tree/feature/worker-min-max

If acceptable I can create a pull request. Please let me know if this is what you also looked at:
- list total nodes per min/max of shoot worker group
- labels: project, shoot, worker name, machine type
